server:
  port: 8002
eureka:
  instance:
    hostname: node2
  client:
    serviceUrl:
      defaultZone: http://node1:8001/eureka,http://node3:8003/eureka
    register-with-eureka: true
    fetch-registry: true
spring:
  application:
    name: eureka-server
