cloud:
  hello: hello this is dev update1111
datadb:
  url: jdbc:mysql://47.98.49.140:3306/mp
  ip: 47.98.49.140
  port: 3306
  username: root
  password: 123456
  driver-class-name: com.mysql.jdbc.Driver
person:
  name: xp
  id: 24
  list:
    - a
    - b
    - d
  map: {k1: value1, k2: value2}
