spring:
  application:
    name: spring-cloud-config-client
  datasource:
    url: jdbc:mysql://${datadb.ip}:${datadb.port}/mp
    username: ${datadb.username}
    password: ${datadb.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8002
management:
  endpoints:
    web:
      exposure:
        include: '*'
config:
  test: ${cloud.hello}
db:
  url: ${datadb.url}