spring:
  application:
    name: spring-cloud-zuul
server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
zuul:
  routes:
    api-a:
      path: /producer/**
      serviceId: spring-cloud-producer
    api-b:
      path: /consumer/**
      serviceId: spring-cloud-consumer
